"""CRUD for the Actions sheet in Google Sheets using a service account.

The Actions sheet stores planned outreach actions (emails and calendar events)
generated by the outreach agent during a dry-run.  Each row represents one
action awaiting user approval.

Column layout matches schemas/sheet_config.ActionColumns (0-based):
    A  id
    B  kind            (email | calendar)
    C  status          (pending | confirming | confirmed | canceled)
    D  created_at
    E  confirmed_at
    F  email_type
    G  recipient_email
    H  recipient_name
    I  subject
    J  people_id
    K  event_type
    L  event_title
    M  attendees       (comma-separated)
    N  start_time
    O  end_time
    P  demo_id
"""

import os
from typing import Optional

import gspread
from google.oauth2.service_account import Credentials

_SCOPES = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

_HEADER = [
    "id", "kind", "status", "created_at", "confirmed_at",
    "email_type", "recipient_email", "recipient_name", "subject", "people_id",
    "event_type", "event_title", "attendees", "start_time", "end_time", "demo_id",
]


_gspread_client = None
_spreadsheet = None
_actions_ws = None


def _get_sheet():
    """Return the Actions worksheet, creating it (with header) if absent. Caches client/sheet."""
    global _gspread_client, _spreadsheet, _actions_ws
    if _actions_ws is not None:
        return _actions_ws
    creds_file = os.getenv("GOOGLE_CREDENTIALS_FILE", "credentials.json")
    sheet_id = os.environ["GOOGLE_SHEET_ID"]
    if _gspread_client is None:
        creds = Credentials.from_service_account_file(creds_file, scopes=_SCOPES)
        _gspread_client = gspread.authorize(creds)
    if _spreadsheet is None:
        _spreadsheet = _gspread_client.open_by_key(sheet_id)
    try:
        _actions_ws = _spreadsheet.worksheet("Actions")
    except gspread.WorksheetNotFound:
        _actions_ws = _spreadsheet.add_worksheet(title="Actions", rows=1000, cols=len(_HEADER))
        _actions_ws.append_row(_HEADER, value_input_option="RAW")
    return _actions_ws


# ---------------------------------------------------------------------------
# Row ↔ dict conversion helpers
# ---------------------------------------------------------------------------

def _row_to_dict(row: list) -> dict:
    def _c(col: int) -> str:
        return row[col].strip() if col < len(row) else ""

    attendees_raw = _c(12)
    attendees = [a.strip() for a in attendees_raw.split(",") if a.strip()] if attendees_raw else []

    return {
        "id": _c(0),
        "kind": _c(1),
        "status": _c(2),
        "created_at": _c(3),
        "confirmed_at": _c(4) or None,
        "email_type": _c(5) or None,
        "recipient_email": _c(6) or None,
        "recipient_name": _c(7) or None,
        "subject": _c(8) or None,
        "people_id": _c(9) or None,
        "event_type": _c(10) or None,
        "event_title": _c(11) or None,
        "attendees": attendees,
        "start_time": _c(13) or None,
        "end_time": _c(14) or None,
        "demo_id": _c(15) or None,
    }


def _dict_to_row(action: dict) -> list:
    attendees = action.get("attendees") or []
    attendees_str = ", ".join(attendees) if isinstance(attendees, list) else str(attendees)
    return [
        action.get("id", ""),
        action.get("kind", ""),
        action.get("status", "pending"),
        action.get("created_at", ""),
        action.get("confirmed_at", "") or "",
        action.get("email_type", "") or "",
        action.get("recipient_email", "") or "",
        action.get("recipient_name", "") or "",
        action.get("subject", "") or "",
        action.get("people_id", "") or "",
        action.get("event_type", "") or "",
        action.get("event_title", "") or "",
        attendees_str,
        action.get("start_time", "") or "",
        action.get("end_time", "") or "",
        action.get("demo_id", "") or "",
    ]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_actions(status_filter: Optional[str] = None) -> list:
    """Return actions from the sheet, optionally filtered by a single status value."""
    sheet = _get_sheet()
    rows = sheet.get_all_values()
    if not rows or len(rows) < 2:
        return []

    result = []
    for row in rows[1:]:  # skip header
        if not row or not row[0].strip():
            continue
        action = _row_to_dict(row)
        if status_filter is None or action["status"] == status_filter:
            result.append(action)
    return result


def get_action_by_id(action_id: str) -> Optional[dict]:
    """Return a single action dict by ID, or None if not found."""
    for action in get_actions():
        if action["id"] == action_id:
            return action
    return None


def write_actions(actions: list) -> None:
    """Append action rows to the sheet."""
    if not actions:
        return
    sheet = _get_sheet()
    rows = [_dict_to_row(a) for a in actions]
    sheet.append_rows(rows, value_input_option="RAW")


def update_action_status(
    action_id: str,
    status: str,
    confirmed_at: Optional[str] = None,
) -> None:
    """Find a row by action_id and update its status (and optionally confirmed_at)."""
    sheet = _get_sheet()
    rows = sheet.get_all_values()
    for i, row in enumerate(rows):
        if i == 0 or not row:
            continue
        if row[0].strip() == action_id:
            row_num = i + 1  # 1-based
            cells = [gspread.Cell(row_num, 3, status)]  # col C = status
            if confirmed_at:
                cells.append(gspread.Cell(row_num, 5, confirmed_at))  # col E = confirmed_at
            sheet.update_cells(cells)
            return


def batch_update_action_status(
    action_ids: list,
    status: str,
    confirmed_at: Optional[str] = None,
) -> None:
    """Update status for multiple actions in one sheet call."""
    if not action_ids:
        return
    sheet = _get_sheet()
    rows = sheet.get_all_values()
    id_set = set(action_ids)
    cells = []
    for i, row in enumerate(rows):
        if i == 0 or not row:
            continue
        if row[0].strip() in id_set:
            cells.append(gspread.Cell(i + 1, 3, status))
            if confirmed_at:
                cells.append(gspread.Cell(i + 1, 5, confirmed_at))
    if cells:
        sheet.update_cells(cells)


def cancel_pending_actions() -> None:
    """Mark all actions with status='pending' as 'canceled'."""
    sheet = _get_sheet()
    rows = sheet.get_all_values()
    cells = []
    for i, row in enumerate(rows):
        if i == 0 or not row:
            continue
        if len(row) > 2 and row[2].strip() == "pending":
            cells.append(gspread.Cell(i + 1, 3, "canceled"))
    if cells:
        sheet.update_cells(cells)


def clear_all_actions() -> None:
    """Mark ALL action rows as 'canceled' (used before writing a fresh plan batch)."""
    sheet = _get_sheet()
    rows = sheet.get_all_values()
    cells = []
    for i, row in enumerate(rows):
        if i == 0 or not row or not row[0].strip():
            continue
        if len(row) > 2 and row[2].strip() != "canceled":
            cells.append(gspread.Cell(i + 1, 3, "canceled"))
    if cells:
        sheet.update_cells(cells)
